# Configuration file for command line utility

# The name of the directory with dictionary files
DictionaryDir: data

# Dictionary files to load
LUFiles: testdict.tsv

# IndexCorpus is the name of the corpus for the term frequency index in Firestore.
IndexCorpus: cnreader

 # IndexGen gets the generation number for the term frequency index in Firestore.
IndexGen: 0
