# Configuration file for web application

# Directory for Go templates for dynamically rendered pages
#TemplateDir: templates
# For Material Design Web components
TemplateDir: web-resources

# Title for Go generated HTML pages
Title: Chinese Notes Translation Portal

# The ID of a user to send mail from
FromEmail: do_not_reply@example.com

# The URL for a password reset
PasswordResetURL: http://localhost:8080/loggedin/reset_password

 # Regular expression for extracting multilingual equivalents in the notes.
NotesExtractorPattern: "Scientific name: (.*?)[\(,\,,\;]","Species: (.*?)[\(,\,,\;]"
